# Generated by Django 3.0.5 on 2020-04-26 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('babys', '0002_auto_20200426_1209'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='dateTime',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_type',
        ),
        migrations.AlterField(
            model_name='event',
            name='baby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='babys.Baby'),
        ),
    ]
