# Generated by Django 3.0.5 on 2020-04-26 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0001_initial'),
        ('babys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baby',
            name='lastname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='baby',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parents.Parent'),
        ),
    ]
